<h3 align=center><font color="darkgreen" size="12">NumPy</h3>
<h4 align=center>Numerical python package is stand for make numerical computation more easy by providing a lot of mathematical arrangement and functionality. Numpy package allow us to create multi-dimensional arrays and and thier usfull functionality</h4>

<br>

<b>Dimension</b>

    Dimension of a mathematical shape is informally defined as the minimum number of co-ordinates
    needed to spacify any point within it. Like, the inside of a cube, cylinder, or a sphere 
    is three dimension because three co-ordinates (x,y,z) are needed to locate a point with in 
    these spaces. Similarly for a circle there need two co-ordinates (x,y);so, circle is two dimension
    (-Wikipedia)
   
<br>
<b>Shape and n-D Array</b>
    
    Array can be 1D,2D,3D or nD on the otherhand matrix is 2D representation of an array
    
    [
        [
            [1,2,3],[1,2,3],[1,2,3]
        ],
        [
            [4,5,6],[4,5,6],[4,5,6]
        ]
    ]
    this is 3D or 3-dimensional array which shape is (2*3*3)
    
    
<br>
<b>Matrix and Vector</b>

    A matrix is simply a rectangular array of numbers and a vector is a row or a column of a matrix;
    for a (n*m) shaped matrix a vector can be considered  as (n*1) or (1*m) shaped matrix.
    (-Quora)
    
<br>
<b>Numpy axis</b> 

    In Numpy dimensions are called axis. The number of axis is rank. For example, the co-ordinates
    of a point in 3D space(x,y,z) [2,3,5] is an array of rank 1 because this is an 1D array and so
    that it has one axis. That axis has a lenght of 3.Representation of this array:
    [
        2,
        3,
        5
    ]
    So, shape is (3,0) or (3,)
    
    axis(-1) or last axis refer the row; it comes like this (... <-depth <-column <-row)
    The more dimensional we have the the more axis we have to handle. So it is important 
    to visualize or imagine the dimensionality 
    
    [
        [0,0,0],
        [1,2,3],
        [2,2,2],
        [9,9,9]
    ] 
    this is a matrix or a 2D array which represent 4 points of a **3D geometrical space** and shape (4,3).
    Dimension of this array is 2. 
   <b><font color="red">Don't mix up array's dimension and geometrical dimension.</b>

In [1]:
import numpy as np

<br>
<b>Data Types</b>
    
    Integers: np.int8, np.int16, np.int32, np.int64
    Fractions: np.float16, np.float32, np.float64
    Complex: np.complex64, np.complex128
    Others: np.bool
<br>
<b>Arrays</b>
    
    >>arr = numpy.array(lists, dtype=None)
    this api format of array is use most. where lists is python list and dtype is numpy
    datatype. default integer is np.int32 and fraction is np.float64
    >>arr.dtype
    this state will return the data type of this array
    >>arr.ndim
    this will return the array dimension
    >>arr.shape 
    this will return the array shape
    >>arr.size
    this will return the size or more precisely the total amount of base element;
    like, array([[1,2],[3,1]]) for this size=4 (number of total dtype element)
    >>arr.reshape(new_shape)
    this api will return the new shape of our array.
    *** the arrangement of new and old shape must be equal; like we have a (2*3) shaped
    array, our new shape can be (3*2), (1,6), (6,1) as because
    2*3 = 3*2 = 1*6 = 6*1 = 6 (number of size)

In [2]:
a = np.array([1,4,2,6], dtype=np.float32) #defining an numpy array with custom data type
print(a.dtype) #print out the data type
print(a.ndim) #print out the dimension of this array
print(a.shape) #print out the shape of this array
print(a.size) #print out the total number of element

float32
1
(4,)
4


In [3]:
a = np.array([[1,3],[4,4],[5,2],[9,7]]) #defining a new numpy array
print(a.shape) #print out its shape
print(a.ndim) #print out its dimension
a = a.reshape((2,2,2)) #reshape the array and store it
print(a.shape) #print out the new shape
print(a.ndim) #print out the new dimension
print(a) #print out the new array

(4, 2)
2
(2, 2, 2)
3
[[[1 3]
  [4 4]]

 [[5 2]
  [9 7]]]


<br>
<b>Array create</b>

    >>numpy.arange(start=0, stop=None, step=1, dtype=None)
    this api allow us to create a 1D array with defined range and steps.
    Like for start=2, stop=5 -> array(2,3,4) and for start=1, stop=7, step=2 ->
    array(1,3,5).
    >>numpy.arange(5)
    this will create an array like this -> (0,1,2,3,4)
    
    To create a multidensional array just use reshape() method after arange an array.
    >>numpy.arange(6).reshape((2,3))
    this script will return an array like this -> ([[0,1,2],[3,4,5]])
    Remember (stop-start)/step must be equal to product of the shape. Like for n*m shape
    (stop-start)/step = n*m
    
    For fractional steps like start=1, stop=13, step=3.53 then, use float data types
    otherwise use start=1.0 or stop=13.0. Nor program will get an error
    
    >>numpy.zeros(shape)
    this api will return a defined shaped array - elements of zeros
    >>numpy.ones(shape)
    this api will return a defined shaped array - elements of ones

In [4]:
print(np.arange(start=1,step=4.3,dtype=np.float32,stop=13)) #unordered params with defined args name
print(np.arange(30,45,4.5,np.float32)) #ordered params with undefined args name
print(np.arange(30.0,45,4.5)) #using start as fraction for fractional steps
print(np.arange(30,45.0,4.5)) #using stop as fraction for fractional steps

[1.  5.3 9.6]
[30.  34.5 39.  43.5]
[30.  34.5 39.  43.5]
[30.  34.5 39.  43.5]


In [5]:
print(np.arange(6).reshape(2,3)) #creating a 2D array with defined shape and size
print(np.arange(2*4).reshape(2,4)) #creating an array more precisely 

[[0 1 2]
 [3 4 5]]
[[0 1 2 3]
 [4 5 6 7]]


In [6]:
print('zeros:\n',np.zeros((3,4)))
print('ones:\n',np.ones((3,3)))
      

zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<br>
<b>Sorting</b>

    >>arr = numpy.array([4,1,2,0])
    >>numpy.sort(arr)
    this api return a sorted copy of this array; this is a simple form of numpy sort
    
    >>numpy.sort(arr, axis=-1, kind='quicksort', order=None)
    this is the default sort api form where arr is the array to be sorted, axis=-1 refer the 
    row of the array use for comparism and kind refer the sorting algorithm to be followed and 
    order is for dictionary,map or list type array where key is used as the base of comparism; like
    we have a string array of 10 human data where we have their age, id and name, so this 3 key can be
    use for ordering the array or sorting.
    
    Numpy has 3 kind of sorting algorithm: 'quicksort'(default), 'mergesort' and 'heapsort'.
    
    The most important things of this sort api is the axis. For example we take an array 
    [
        [
            [4,3,5],
            [2,3,4]
        ],
        [
            [1,2,3],
            [2,6,3]
        ]
    ]
    this is a 3-dimensional array of shaped (2,2,3), so there are 3 axes here-axis(0),axis(1) and axis(2)
    where axis(2) or axis(-1)=row relation, axis(1)=column relation and axis(0)=depth relation. If we have 
    greater than 3-dimension then there will more dimensional relation here.
    Here we try to visualize the relation between axes and how to be sorted by this relation
<img src='resources/axis_relation.jpg' heigh=200px width=800px, align='left'>

In [7]:
arr = np.array([[[4,3,5],[2,3,4]],[[1,2,3],[2,6,3]]]) #defining the array
print(arr.shape) #print out the shape of this array
print(arr.ndim) #print out the dimension of this array

(2, 2, 3)
3


In [8]:
np.sort(arr) #sort the array with default axis(-1) or based on row-relation

array([[[3, 4, 5],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 6]]])

In [9]:
np.sort(arr, axis=2) #sort the array with axis(2) which is already have done by axis(-1)

array([[[3, 4, 5],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 6]]])

In [10]:
np.sort(arr, axis=1) #sort the array with the axis(1) or based on column-relation

array([[[2, 3, 4],
        [4, 3, 5]],

       [[1, 2, 3],
        [2, 6, 3]]])

In [11]:
np.sort(arr, axis=0) #sort the array with the axis(0) or based on depth-relation

array([[[1, 2, 3],
        [2, 3, 3]],

       [[4, 3, 5],
        [2, 6, 4]]])

In [12]:
np.sort(arr, axis=None) #by set axis=None array will be flatted and then sort

array([1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 6])

##### more:
    there are two more sorting module available in numpy; one in argsort and another is lexsort.
    argsort simply return the sorted index instead of value of the array, like [4(0),3(1),7(2)] ->
    argsort will return [1{3},0{4},2{7}]
    >>numpy.argsort(arr, axis=-1, kind='quicksort', order=None)
    this is the default api of argsort function in numpy
    
    lexsort work based on another same length array from where it get the pattern and sort with 
    that and return the indices instead of value
    >>numpy.lexsort((a,b), axis=-1) where a will be sorted based on b's pattern

In [13]:
np.argsort(arr, kind='heapsort') #print out the axis=2 based sorting indices by using heapsort algo

array([[[1, 0, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 2, 1]]], dtype=int64)

In [14]:
a = np.array([4,2,3,5]) #create a numpy array named 'a'
b = np.array([1,6,2,4]) #create another named 'b'
np.lexsort((a,b)) #sort a based on b 

array([0, 2, 3, 1], dtype=int64)

<br>
<b>Sum and Average</b>
    
    >>numpy.sum(arr,axis=None,dtype=None,out=None,keepdim=False)
    this is the api form of sum method.
    Concentrate on axis, by default this set to None, so the whole array transform to flat array
    or 1D form then sum will perform more precisely this way will sum all element at once
    If we want to sum elements based on axis or dimension then use axis number. 
    
    >>numpy.average(arr,axis=None,weight=None,returned=False)
    formally this api will return the average of the flatted form of the array we passed.
    For axis based average we need to put the valid axis. Generally in average formula we 
    take 50% or 0.5 portion of every element. Like average of (3,4) = 3.5, where (3+4)/2
    or 3/2 + 4/2 = 3*0.5 + 4*0; here (0.5 and 0.5) is the weight. So weight refer the 
    custom properties for make average. For this (3,4) if we take our weight (0.2,0.8)
    instead of (0.5,0.5) our answer will be (3*0.2 + 4*0.8) = 0.6 + 3.2 = 3.8
    weights sum must be equal to 1 => (0.2+0.8) => (0.5+0.5)

In [15]:
a = np.array([[[4,3,5],[2,3,4]],[[1,2,3],[2,6,3]]]) #defining our array
print(a.shape) #print out the shape of this array
print(a.ndim) #print out the dimension of this array

(2, 2, 3)
3


In [16]:
print('basic form: ', np.sum(a)) #useing basic form of sum api which will sum the flatted array
print('axis=None: ', np.sum(a, axis=None)) #using axis=None which refer the basic form 
print('axis=0: \n', np.sum(a, axis=0)) #sum the array based on axis=0 or row-relation
print('axis=1: \n', np.sum(a, axis=1)) #sum the array based on axis=1 or column-relation
print('axis=2: \n', np.sum(a, axis=2)) #sum the array based on axis=2 or axis=-1 or deoth-relation

basic form:  38
axis=None:  38
axis=0: 
 [[5 5 8]
 [4 9 7]]
axis=1: 
 [[6 6 9]
 [3 8 6]]
axis=2: 
 [[12  9]
 [ 6 11]]


In [17]:
ar = np.array([[1,2],[3,4]]) #define a numpy array
print('Flatted Array: ', np.reshape(ar,(1,4)))
print('Flatted average: ', np.average(ar))
print('Main array: \n', ar)
print('axis(0) average: ', np.average(ar, axis=0))
print('axis(1) average: ', np.average(ar, axis=1))
print('axis(0) with weights: ', np.average(ar,axis=0,weights=[0.9,0.1]))
print('axis(1) with weights: ', np.average(ar,axis=1,weights=[0.3,0.7]))

Flatted Array:  [[1 2 3 4]]
Flatted average:  2.5
Main array: 
 [[1 2]
 [3 4]]
axis(0) average:  [2. 3.]
axis(1) average:  [1.5 3.5]
axis(0) with weights:  [1.2 2.2]
axis(1) with weights:  [1.7 3.7]


<br>
#### Modification
    >>numpy.zeros_like(arr)
    this will return an array of zeros instead of passed array's elements
    
    >>numpy.ones_like(arr)
    this will return an array of ones instead of passed array's elements
    
    >>numpy.append(arr,value,axis=None)
    this will append a new value in the defined axis of the array we passed into it.
    In general this api will flatted the inputed array then append values whatever you passed.
    If we want append a row, or a column or precisely we want to append values into defined axis
    then we must input the valid shape array as value in the defined axis otherwise it will get 
    an error.
    
    >>numpy.around(arr, decimal=0, out=None)
    this api is for fractional number. like we have some elements 3.13131231, 5.32424242
    and this api will make elements into defined decimal number like for 2 decimal
    3.13, 5.32

In [18]:
arr = np.array([[1,2],[3,4]])
print('zeros:\n',np.zeros_like(arr))
print('ones:\n',np.ones_like(arr))

zeros:
 [[0 0]
 [0 0]]
ones:
 [[1 1]
 [1 1]]


In [19]:
arr = np.array([[1,2],[3,4]])
print('main array:\n', arr)
arr1 = np.append(arr, [[5,6],[7,8]], axis=0)
print('axis(0):\n', arr1)
arr2 = np.append(arr, [[5,6],[7,8]], axis=1)
print('axis(1):\n', arr2)
print('flatted:',np.append(arr,[10]))

main array:
 [[1 2]
 [3 4]]
axis(0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
axis(1):
 [[1 2 5 6]
 [3 4 7 8]]
flatted: [ 1  2  3  4 10]


In [20]:
arr = np.array([3.6774,1.23232]) #defining an array of fractional numbers
np.around(arr, 3) #print the array with 3 decimal number

array([3.677, 1.232])

<br>
#### Explore
    >>numpy.all(arr,axis=None,out=None,keepdim=False)
    this api will check whether a single zero exist in a defined axis
    
    >>numpy.any(arr,axis=None,out=None,keepdim=None)
    this api will check whether a single non-zero element exist or not
    
    >>numpy.alltrue(arr,axis=None,out=None,keepdim=False)
    this api will check whether all elements are true, if all are true then this will return true
    otherwise this will return false
    
    >>numpy.amax(arr,axis=None,out=None,keepdim=False)
    Remember the axis relation. As the default axis=None so this api will flat the array first then
    find out the maximum element among them. For row-relation(axis=-1) it will just represent an array 
    from each row's maximum. For other relations like column-relation or depth-relation it will
    represent the array from maxmum of each relation; like [[1,2],[4,1]] it will give [4,2] for axis(1)
    Just follow the below code for better understand
    
    >>numpy.amin(arr,axis=None,out=None,keepdim=False)
    this will just return the minimum
    
    >>numpy.argmax(arr,axis=None,out=None,keepdim=False)
    this api will return the index or indices of maximum values
    
    >>numpy.argmin(arr,axis=None,out=None,keepdim=False)
    this api will return the index or indices of minimum values

In [21]:
arr = np.array([[0,0],[123,0]])
print(np.all(arr))
print(np.any(arr))
print(np.alltrue(arr))

False
True
False


In [22]:
x = np.array([[[1,20,3],[4,5,6]],[[9,8,-7],[6,5,4]]]) #define an numpy array
print(x.ndim) #print out the dimension of this array

3


In [23]:
print('Max-Value:')
print('axis=None\n', np.amax(x))
print('axis=0\n', np.amax(x,axis=0))
print('axis=1\n', np.amax(x,axis=1))
print('axis=2\n', np.amax(x,axis=2))

Max-Value:
axis=None
 20
axis=0
 [[ 9 20  3]
 [ 6  5  6]]
axis=1
 [[ 4 20  6]
 [ 9  8  4]]
axis=2
 [[20  6]
 [ 9  6]]


In [24]:
print('Min-Value:')
print('axis=None\n', np.amin(x))
print('axis=0\n', np.amin(x,axis=0))
print('axis=1\n', np.amin(x,axis=1))
print('axis=2\n', np.amin(x,axis=2))

Min-Value:
axis=None
 -7
axis=0
 [[ 1  8 -7]
 [ 4  5  4]]
axis=1
 [[ 1  5  3]
 [ 6  5 -7]]
axis=2
 [[ 1  4]
 [-7  4]]


In [25]:
print('Max-Index or Indices:')
print('axis=None\n', np.argmax(x))
print('axis=0\n', np.argmax(x,axis=0))
print('axis=1\n', np.argmax(x,axis=1))
print('axis=2\n', np.argmax(x,axis=2))

Max-Index or Indices:
axis=None
 1
axis=0
 [[1 0 0]
 [1 0 0]]
axis=1
 [[1 0 1]
 [0 0 1]]
axis=2
 [[1 2]
 [0 0]]


In [26]:
print('Min-Index or Indices:')
print('axis=None\n', np.argmin(x))
print('axis=0\n', np.argmin(x,axis=0))
print('axis=1\n', np.argmin(x,axis=1))
print('axis=2\n', np.argmin(x,axis=2))

Min-Index or Indices:
axis=None
 8
axis=0
 [[0 1 1]
 [0 0 1]]
axis=1
 [[0 1 0]
 [1 1 0]]
axis=2
 [[0 0]
 [2 2]]


##### More
    >>numpy.array_equal(arr1, arr2)
    this will return whether 2 array (same shaped and dimensioned) has same element
    in each indices or more precisely whether they are same or not
    
    >>numpy.array_equiv(arr1, arr2)
    this api check whether they are same or can we make arr1 by using arr2 or arr2
    from arr1. Suppose arr1=[1,2] and arr2=[[1,2],[1,2]]
    here we can make arr2 by using arr1 2 times like [arr1,arr1]=[[1,2],[1,2]], so 
    here we will get True as answer.

In [27]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[1,2],[4,3]])
a3 = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [28]:
print('Checking a1 equal a2: ', np.array_equal(a1,a2))
print('Checking a1 equiv a3: ', np.array_equiv(a1,a3))
print('Checking a3 equiv a3: ', np.array_equiv(a3,a1))

Checking a1 equal a2:  False
Checking a1 equiv a3:  True
Checking a3 equiv a3:  True


<br>
### Number Handling
<br>

#### Base Transform
    >>numpy.base_repr(number, base=2, padding=0)
    this api will transform number to custom base number with padding facilities.
    For decimal number just use the number, for hexadecimal use '0x' before the number,
    like 0xAA and for octal use '0o'; padding means how many zero will be added
    before the transformed number
    
    >>numpy.binary_repr(number, width=None)
    this will transform a number only in binary where width refer the length we
    want. like decimal(2) = binary(10) for widht 4 this will be 0010

In [34]:
print(np.base_repr(4)) #decimal to binary
print(np.base_repr(0xFA)) #hexadecimal to binary
print(np.base_repr(0o6)) #octal to binary

100
11111010
110


In [44]:
print(np.base_repr(4,base=3)) #transform decimal(4) to 3-base
print(np.base_repr(4,base=3,padding=5)) #using padding
print(np.base_repr(4,3),' and ',np.base_repr(4,3,5)) #without args name


11
0000011
11  and  0000011


In [48]:
print(np.binary_repr(4)) #decimal(4) to binary
print(np.binary_repr(4,6)) #decimal(4) to binary in 6 length

100
000100
