<h1 align=center><font size="34" color=#ff4500>Introduction of Tensorflow</h1>
<h2 align=center><font color=#8b0000>Stanford Uninversity</h2>

In [1]:
import tensorflow as tf

#### constant
    tensorflow.constant(value, dtype=None, shape=(), name='const', varify_shape=False)
    constant allow us to define a node in graph. It takes minimum one argument which is value.
    dtype will generate after set the value and name will set 'const', 'const_1',...'const_n' respectively
    where n is natural number. shape will allow us to define n-dimentional array. 
    varify_shape will allow the program check the valid shape as value inputed before execute the graph.
    Suppose we define the value this [[1,2],[3,4]] which is a (2 X 2) matrix, and set the shape (4,3),
    if varify_shape=False then tensorflow will create a (4 X 3) shape using the last element of our value.
    just like = [[1,2,3],[4,4,4],[4,4,4],[4,4,4]] and when we set varify_shape=True then we will get an error
    because tensorflow won't find out the actual shaped value
    
#### Simple arithmetic 
    Tensorflow will allow arithmetic operation only for graph node. Such:
    >>x1 = tensorflow.constant(4) -> a node with the value of 4
    >>x2 = tensorflow.constant(5) -> a node with the value of 5
    then do the arithmetic operation using a+b, a*b, a/b, a-b, a**b, a%b whatever python support.
    If we don't set any node in graph before operation then another way to do this is:
    >>tensorflow.add(4,5) == 4+5
    >>tensorflow.subtract(4,5) == 4-5
    >>tensorflow.multiply(4,5) == 4*5
    >>tensorflow.divide(4,5) == 4/5
    >>tensorflow.pow(4,5) == 4**5
    >>tensorflow.mode(4,5) == 4%5
    
#### tensorflow data types
    Integers: tf.int8, tf.int16, tf.int32, tf.int64
    Fraction: tf.float16, tf.float32, tf.float64
    Complex: tf.complex64, tf.complex128
    Others: tf.bool, tf.string
    check out tensorflow doc for more varible that are available in tensorflow
    
#### Session
    To execute a tensorflow graph we must need a session to run the graph. To define a session write
    tensorflow.Session() and to run it tensorflow.Session().run(args)
    Generally we define a session just like this: 
    
    >>session = tensorflow.Session() and then session.run(args) or
    
    >>with tensorflow.Session() as session:
      ... session.run(args)
    
    After executed our graph we must close the session otherwise it will conflict with other session.
    To close a session just write >>session.close()
    
    Another kind of session available in tensorflow which is for instant execution.
    >>tensorflow.InteractiveSession()
    this will allow us to execute a graph or subgraph or a node instantly
    More about session will discuss letter

In [2]:
x1 = tf.constant(16) #create a node in graph with the value of 16
x2 = tf.constant(18) #create a node in graph with the value of 18

with tf.Session() as ses: #create a session in with clause
    print(ses.run(x1+x2)) #run and print the addtion value of x1 and x2
    ses.close() #close this session

34


In [3]:
w1 = 7 #define a value 
w2 = 3 #define a value

x1 = tf.subtract(w1, w2, name='in1') #define a node in graph name 'in1' with the subtraction value of w1 and w2 
x2 = tf.add(w1, w2, name='in2') #define a node in graph name 'in2' with the additional value of w1 and w2

y = tf.pow(x1, x2, name='out') #define a node in graph name 'out' with the value of x1^x2

with tf.Session() as ses: #create a session name as ses
    '''
    when we execute node y, tensorflow will find out the value of x1 and x2 first, so tensorflow will execute
    x1 = w1 - w2 and x2 = w1 + w2 and the come to y and execute it and then store the execution value in y 
    '''
    y = ses.run(y) #execute node y 
    print(y) #print the value of y
    ses.close() #close the session

1048576


In [4]:
x1 = tf.multiply(4,3) #here, x1 = 4*3 = 12
x2 = tf.pow(4,3) #here, x2 = 4^3 = 64

y1 = tf.add(x1,x2) #here, y1 = 12+64 = 76
y2 = tf.subtract(x1,x2) #here, y2 = 64-12 = 52

with tf.Session() as ses:
    print(ses.run([y1,y2])) #run session with node array
    ses.close()

[76, -52]


<br>
#### Graph
    As tensorflow work with data flow graph, so there is a default graph provide by tensorflow
    It is better to work with in a single graph, and use many sub-graph for one single graph
    But when-ever you need a graph just write the module tensorflow.Graph() and will return a graph
    >>g = tensorflow.Graph()
    
    When you we use 2 or more graph in a single program then we must handle each graph
    when we need to add a node in a custom graph or use a custom graph we first define it as default, like
    >>g.as_default()
    then this custom graph will be our workplace.
    
    to get default graph use
    >>g = tf.get_default_graph()
    
    More about tensorflow graph will discuss letter

In [5]:
g = tf.Graph() #create a new graph
with g.as_default(): #set it as default then define node x with addtion of 3 and 4
    x = tf.add(3,4) #without make this graph as default our node will create in tensorflow default graph
    
with tf.Session(graph = g) as ses: #create a session for our defined graph by passing as arg
    print(ses.run(x)) #run this session
    ses.close() #close the session

7


In [6]:
print(tf.get_default_graph()) #by default graph provide by tensorflow
g = tf.Graph() #create a new graph
with g.as_default(): #make it as default in with block
    print(tf.get_default_graph()) #check out default graph

In [7]:
g = tf.Graph() #create a new graph
a = tf.constant(3) #define node a with value of 3 in by default graph
with g.as_default(): #call our custom graph as default
    b = tf.constant(4) #define node b there with value of 4
with tf.Session() as ses: #create a session for by default graph
    print(ses.run(a)) #print out its node a
with tf.Session(graph = g) as ses: #create a session for our custom graph by passing arg
    print(ses.run(b)) #print out its node b

3
4


<br>
#### Tensorflow Graph Visualization
    >>a = tf.constant(2)
    >>b = tf.constant(3)

    >>m = tf.add(a,b)
    >>with tf.Session() as ses:
      ...writer = tf.summary.FileWriter('./graphs',ses.graph)
      ...print(ses.run(m))
      ...writer.close()
      ...ses.close()
        
    #terminal : tensorboard --logdir="./graphs" --port = XXXX
    #browser : localhost:XXXX

<br><p><b><font color='Green'>Creating tensorflow Interactive Session for instant execution</b></p>

In [8]:
tf.InteractiveSession()

>### <font color="darkblue">Instant and random tensor create<br>

In [9]:
x = tf.zeros((2,3), dtype=tf.float32,name='zeros') #creating a matrix of 2X3 shaped with zeros
x.eval() #instant execute

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

    >>tensorflow.zeros(shape=None, dtype=None, name=None)
    this api provide to create a defined shape matrix where all elements are zero;
    let we need [[0,0,0],[0,0,0]] which is a matrix of 2X3 where all elements are zero.

In [10]:
x = tf.ones((4,2), dtype=tf.int8, name='ones') #creating a matrix of 4X2 shaped with ones
x.eval() #instant execute

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

    >>tensorflow.ones(shape=None, dtype=None, name=None)
    this api provide to create a defined shape matrix where all elements are one;
    let we need [[1,1],[1,1],[1,1],[1,1]] which is a matrix of 4X2 where all elements are one.

In [11]:
x = tf.fill((3,3), 13)
x.eval()

array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

    >>tensorflow.fill(shape=None, value, name=None)
    this api provide to create a defined shape matrix with the defied value
    let we need a matrix of 3X3 where all elements are 13, this is our code to write

In [12]:
x = tf.linspace(3.0, 8.0, 3) #here start element= 3.0 , stop element= 5.0 and array length = 3
x.eval() #instant execuet

array([3. , 5.5, 8. ], dtype=float32)

    >>tensorflow.linspace(start=None, stop=None, num=None, name=None)
    this api provide to create a one dimensional array of num lenght which start and stop with defined value.
    Here we use start=3.0 instead of 3 and stop=8.0 instead of 8, as because our array length will be 3, and
    for this our data type in this range should be in float type. As this api does not take data type so we have
    to use this kind of technique

In [13]:
node = [[3,6],[9,12]] #predefined matrix
x = tf.zeros_like(node, tf.int32, name='zeros') #creating a matrix of node shaped with zeros
x.eval() #instant execute

array([[0, 0],
       [0, 0]])

    >>tensorflow.zeros_like(tensor_node=None, dtype=None, name=None)
    this api provide to create a matrix of passed node shaped with zeros,
    let we have a matrix of (N X M) shaped and we need another matrix of this shaped
    with all zeros, then this api will be use for this purpose

In [14]:
node = [[3,6],[9,12]] #predefined matrix
x = tf.ones_like(node, tf.int32, name='zeros') #creating a matrix of node shaped with ones
x.eval() #instant execute

array([[1, 1],
       [1, 1]])

    >>tensorflow.ones_like(tensor_node=None, dtype=None, name=None)
    this api provide to create a matrix of passed node shaped with ones,
    let we have a matrix of (N X M) shaped and we need another matrix of this shaped
    with all ones, then this api will be use for this purpose

In [15]:
a = tf.range(start=1, limit=18, delta=2, dtype=tf.int32, name='range') #creating a 1D array will defined range
a.eval() #instant execute

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

    >>tensorflow.range(start=None, limit=None, delta=None, dtype=None, name=None)
    this api provide to create a one dimensional array in defined range where (element_i - element_i-1 = delta),
    let we need a one-dimension array which is start with 1 and should be in 18 where difference between (i+1)th
    and (i)th will equal to delta

In [16]:
a = tf.random_normal(shape=(2,),mean=3.0,stddev=1.5,dtype=tf.float32,seed=None,name=None)
a.eval()

array([4.59045   , 0.03688478], dtype=float32)

    >>tensorflow.random_normal(shape=None, mean=None, stddev=None, dtype=None, seed=None, name=None)
    this api will provide to create a defined shaped array where approximate mean and standard deviation 
    values are predefined. 

In [17]:
a = tf.truncated_normal(shape=(1,2),mean=0.2,stddev=1.4,dtype=tf.float32,seed=None,name=None)
a.eval()

array([[-0.91845614,  0.00353716]], dtype=float32)

    Description will be added

In [18]:
a = tf.random_uniform(shape=(2,1),minval=0,maxval=None,dtype=tf.float32,seed=None,name=None)
a.eval()

array([[0.27349746],
       [0.40021193]], dtype=float32)

    Description will be added

In [19]:
a = tf.random_shuffle([[1,2,9],[3,4,8],[5,6,7]])
a.eval()

array([[1, 2, 9],
       [3, 4, 8],
       [5, 6, 7]])

    >>tensorflow.random_shuffle(value, seed=None, name=None)
    this api allow us to shuffle a n-dimensional array randomly
    shuffle will operate in rows only not the columns

In [20]:
x = [[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]]
a = tf.multinomial(logits=x,num_samples=5,seed=None,name=None)
a.eval()

array([[2, 1, 2, 1, 1],
       [0, 0, 1, 2, 0],
       [0, 2, 1, 2, 2]], dtype=int64)

    Description will be added

In [21]:
a = tf.random_gamma(shape=[5],alpha=[3,9],beta=None,dtype=tf.float32,seed=None,name=None)
a.eval()

array([[ 0.40528718, 13.115233  ],
       [ 1.9820431 ,  6.4917865 ],
       [ 2.4109356 , 10.122631  ],
       [ 0.9669662 , 16.374447  ],
       [ 2.4382353 ,  7.1763825 ]], dtype=float32)

    Description will be added

<br>
#### Placeholder
    In computetion we often need to use equation(y = 2x) or function(f(x) = 2x) or variable(x1,x2)
    instead of constant like (2,3). Suppose we have a function of x, y = 2x+5, and we need to check
    the value of y for x = 2,3,4,5,.... many more of x. To make this operation easy tensorflow provide
    placeholder. In placeholder we use dictionary instead of predefined value. 
    More precisely: let we have x1 = [1,2,3] and x2 = [4,5,6], we need to add them; at certain point 
    we recongnize that x1 should not this for our purpose, and we need to check out some other value of
    x1. So, we have to define x1 as a placeholder of (3,) shaped or 3 dimension and check out some random value.
    To define a placeholder just write
    
    >>x1 = tensorflow.placeholder(dtype=None, shape=None, name=None)
    
    if we set x1 = [0,0,0] then our additional value will be [4,5,6]
    if we set x1 = [4,5,6] then our additional value will be [8,10,12]
    
    placeholder simply allow us to use function or variable instead of constant
   <br><b>Note:
    > 2 = Scaler
    > [2,2,2] = Vector (3 dimensional)
    > [[1,2],[3,4]] = Matrix (2 X 2)
    > [[[1,2],[3,4]],[[5,6],[7,8]]] = Tensor (2 X 2 X 2) {n-dimensional array}

In [22]:
x1 = tf.placeholder(dtype=tf.int32, shape=(3,)) #creating a placeholder of 3 dimension
x2 = tf.constant([4,5,6]) #define a constant of 3 dimension

with tf.Session() as ses: #create a session for execution
    y = ses.run(x1+x2, {x1:(1,2,3)}) #use python dictionary for pick the placeholder value
    ses.close() #close the session
y #show the value of y

array([5, 7, 9])

In [23]:
x1 = tf.placeholder(dtype=tf.int32, shape=(3,))
x2 = tf.constant([4,5,6])

with tf.Session() as ses:
    y = ses.run(x1+x2, {x1:(4,5,6)})
    ses.close()
y

array([ 8, 10, 12])

In [24]:
x1 = tf.add(2,5) #define a node x1 with the value of 2+5
x2 = tf.add(x1,3) #define a node x2 with the additional value of x1 and 3

with tf.Session() as ses: #create a session for execution
    replace_dictionary = {x1:10} #create a dictionary for x1
    y = ses.run(x2, feed_dict=replace_dictionary) #pass the dictionary as feed_dict parameter in run
    ses.close() #close the session
y #show the value of y for x1 = 10: -> y = 10+3 = 13 instead of 7+3=10

13

#### Variable
    Variable is a class in tensorflow which allow us to create variable. In tensorflow constant is
    a method where Variable is a class. Variable class has different functionality than constant. 
    Variable class allow us to change and update a node where constant only allow us to create a node which has
    no update functionality, morever variable allow us to create a node with out any value using identifier
    like x,y,z on the other-hand in constant value must be setted.
    Besides there are more difference between them. Variable class has 4 basic
    functionality: 1.initialization, 2.read, 3.write and 4.update. Variable must be initialize before it
    use in graph.
    

><font size="2"color="darkgreen">Initialization:
        1. instant variable initialization 
        2. initializer for a set of variable
        3. global initializer for all variable

In [75]:
x1 = tf.Variable(tf.zeros((2,3))) #creating a variable of 2X3 matrix of zeros
with tf.Session() as ses: #creating a session
    ses.run(x1.initializer) #executing instant initialization of x1 variable
    print(ses.run(x1)) #print out the x1 variable
    ses.close() #close the session

[[0. 0. 0.]
 [0. 0. 0.]]


In [73]:
x1 = tf.Variable(tf.zeros((2,3))) #creating a variable of 2X3 matrix of zeros
x2 = tf.Variable(tf.ones((2,3))) #creating a variable of 2X3 matrix of ones
init = tf.variables_initializer([x1,x2], name='node1') #creating a initializer for x1 and x2
with tf.Session() as ses: #creating a session for execution
    ses.run(init) #execute the partial initializer for x1 and x2
    print(ses.run(x1)) #print out the x1 variable 
    print(ses.run(x2)) #print out the x2 variable
    ses.close() #close the session

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [74]:
x1 = tf.Variable(tf.zeros((2,3))) #creating a variable of 2X3 matrix of zeros
x2 = tf.Variable(tf.ones((2,3))) #creating a variable of 2X3 matrix of ones
init = tf.global_variables_initializer() #creating a global initializer for initialize all variables
with tf.Session() as ses: #creating a sessio 
    ses.run(init) #execute the global initializer
    print(ses.run(x1)) #print out the x1 variable
    print(ses.run(x2)) #print out the x2 variable
    ses.close() #close the session

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [82]:
x1 = tf.Variable(19)
x1.assign(100)
with tf.Session() as ses:
    ses.run(x1.initializer)
    ses.run(x1.assign_add(100))
    print(x1.eval())

119


><font size="2"color="darkgreen">Assign:
        1. variable.assign(...)
        2. variable.assign_add(...)
        3. variable.assign_sub(...)
    
   <font color="black">
    
        >>x1 = tensorflow.Variable(...)
        >>tensorflow.Session().run(x1.assign(...))
        this api allow us to restore the update value of the varible. Like we have x1 = 3
        and then we use x1.assign(4) then our x1 variable will be 4.
        
        >>x1 = tensorflow.Variable()
        >>tensorflow.Session().run(x1.assign_add(...))
        this api will allow us to update the variable with the additional value of new and 
        previous value. Like we have x1 = 3 and then we use x1.assign_add(4) then our
        x1 will be 3+4 = 7

        >>x1 = tensorflow.Variable(...)
        >>tensorflow.Session().run(x1.assign_sub(...))
        this api will allow us to update the variable with subtractional value of new and
        previous value. Like we have x1 = 6 and then we use x1.assign_sub(2) then our
        x1 will be 6-2 = 4
        
   <font color="red" size="3"><br>
    assign api will only perform when we execute it. More precisely assign api will<br>
    perform only with in a session execution otherwise this will not perform its operation
    
   <font size="2.5"><br>
    
        Suppose we have a variable x1 = 7 and we make a statement like update = x1.assign(9)
        and then we execute the update statement in session.run() without initialize the x1, 
        then tensorflow will auto initialize x1 with the value of 9 as because we run the 
        update statement where we assign x1 as 9 and this assign api will initialize the x1 as 9
        
        Suppose we define two variable x1 = 7 and x2 = x1.assign(x1 * 2), when we initialize x1 as 7 
        and evaluate x2 then x2 will give us 7*2 = 14 and x1 will update with 14. if we execute the x2
        statement second time then it will give us 28 as because our x1 is 14 and new x1 will be 28.
        
        Each session will maintain its own copy of value. Suppose we have a variable x1 = 4. 
        We have two session to run and we initialize x1 for each session then each session will
        initialize the x1 as 4 and they never share there update value of x1 with each other.
        Like session1 add 3 with x1 then x1 will be 7 for session1 and session2 subtract 3 from 
        x1 then x1 will be 4-3=1 not 7-3=4 because each session maintain their own copies

In [83]:
x1 = tf.Variable(13) #creating a variable with the value of 13
x1.assign(26) #assign a update value outter from the session 
with tf.Session() as ses: #creating a session
    ses.run(x1.initializer) #instant initialization of x1 variable
    print(x1.eval()) #print out x1 variable which will give us 13 instead of 26
    ses.close() #close the session

13


In [90]:
x1 = tf.Variable(13) #creating a variable with the value of 13
with tf.Session() as ses: #creating a session
    ses.run(x1.initializer) #instant initialization of x1 variable
    print(x1.eval()) #print out x1 variable which will give us 13 as the defined value
    x1.assign(26) #update the x1 variable inner state of session
    print(x1.eval()) #print out x1 variable which will give us 13 as we didn't executed it
    ses.close() #close the session

13
13


In [89]:
x1 = tf.Variable(13) #creating a variable with the value of 13
with tf.Session() as ses: #creating a session
    ses.run(x1.initializer) #instant initialization of x1 variable
    print(x1.eval()) #print out x1 variable which will give us 13 as the defined value
    ses.run(x1.assign(26)) #update the x1 variable by execute the assign api in session
    print(x1.eval()) #print out x1 variable which will give us 26 as update value
    ses.close() #close the session

13
26


In [94]:
x1 = tf.Variable(13) #creating a variable with the value of 13
with tf.Session() as ses: #creating a session
    ses.run(x1.initializer) #instant initialization of x1 variable
    print(x1.eval()) #print out x1 variable which will give us 13 as the we defined
    ses.run(x1.assign_add(4)) #execute assign_add api which will make x1 = 13+4 = 17
    print(x1.eval()) #print out x1 variable which will give us 17
    ses.close() #close the session

13
17


In [95]:
x1 = tf.Variable(13) #creating a variable with the value of 13
with tf.Session() as ses: #creating a session
    ses.run(x1.initializer) #instant initialization of x1 variable
    print(x1.eval()) #print out x1 variable which will give us 13 as the we defined
    ses.run(x1.assign_sub(4)) #execute assign_sub api which will make x1 = 13-4 = 9
    print(x1.eval()) #print out x1 variable which will give us 9
    ses.close() #close the session

13
9


In [97]:
x1 = tf.Variable(4) #creating a variable with the value of 4
update = x1.assign(8) #make a statement of assign of the x1
with tf.Session() as ses: #creating a session
    ses.run(update) #no need to initialize x1 because update statement will do that
    print(x1.eval()) #this will give us 8 as because x1 was initialized with 8 in update state
    ses.close() #close the session

8


In [102]:
x1 = tf.Variable(4) #creating a variable with the value of 4
x2 = x1.assign(2*x1) #make an update statement of x1
with tf.Session() as ses: #creating a session
    ses.run(x1.initializer) #instant initialization of x1
    print(x2.eval()) #execute x2 which will give us 2*4=8 and make x1=8
    ses.run(x2) #this will execute x2 again and make x2=8*2=16 and x1=16
    print(x2.eval()) #execute x2 -> x2=16*2=32 and make x1=32
    print(x1.eval()) #execute x1 which will give us 32
    ses.run(x2) #execute x2 again and make x1 = x2 = 64
    print(x2.eval()) #execute x2 which will make print x2=128 and make x1=128
    print(x1.eval()) #execute x1 which will give us 128
    ses.close() #close the session

8
32
32
128
128


In [132]:
x1 = tf.Variable(4) #create a variable with the value of 4
ses1 = tf.Session() #creating session1
ses2 = tf.Session() #creating session2
ses1.run(x1.initializer) #instant initialize x1 in session1
ses2.run(x1.initializer) #instant initialize x1 in session2
print(ses1.run(x1.assign_add(3))) #update x1 for session1 and now x1=4+3=7 for session1
print(ses2.run(x1.assign_add(2))) #update x1 for session2 and now x1=4+2=6 for session2
ses1.close() #close session1
ses2.close() #close session2

7
6


<br>
#### Control Dependencies
    >>tensorflow.Graph.control_dependencies([control_inputs])
    this api allow us control the execution serial of nodes, like we have 5 operation
    in our graph: op1, op2, op3, op4 and op5 and we want op2 and op5 will execute before
    others will have executed. Then we have to use control dependencies for control this.
    If we pass op2 and op5 as control_inputs parameters then our graph will execute op2 
    and op5 before others have executed.

In [145]:
x1 = tf.add(1,2)
x2 = tf.add(3,4)
x3 = tf.add(5,6)
x4 = tf.add(9,1)

g = tf.get_default_graph()
g.control_dependencies([x1,x4])